version: "3.8"

services:
  n8n:
    image: n8nio/n8n:latest
    ports:
      - "5678:5678"
    volumes:
      - ./n8n_data:/home/node/.n8n
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER_FILE=/run/secrets/n8n_user
      - N8N_BASIC_AUTH_PASSWORD_FILE=/run/secrets/n8n_password
      - TZ=Asia/Jakarta
    secrets:
      - n8n_user
      - n8n_password

secrets:
  n8n_user:
    file: ./secrets/n8n_user.txt
  n8n_password:
    file: ./secrets/n8n_password.txt
