services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - n8n_network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
    healthcheck:
      test: ["CMD-SHELL", "until pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}; do echo 'Postgres not ready yet...'; sleep 5; done"]
      interval: 10s
      timeout: 5s
      retries: 20

  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    ports:
      - "${N8N_PORT}:5678"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./n8n_data:/home/node/.n8n
      - ./bootstrap.sh:/docker-entrypoint-init.d/bootstrap.sh
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=${N8N_BASIC_AUTH_USER}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_BASIC_AUTH_PASSWORD}
      - DB_TYPE=${N8N_DB_TYPE}
      - DB_POSTGRESDB_HOST=${N8N_DB_HOST}
      - DB_POSTGRESDB_PORT=${N8N_DB_PORT}
      - DB_POSTGRESDB_DATABASE=${N8N_DB_NAME}
      - DB_POSTGRESDB_USER=${POSTGRES_USER}
      - DB_POSTGRESDB_PASSWORD=${POSTGRES_PASSWORD}
      - TZ=Asia/Jakarta
      - NODE_OPTIONS=--max_old_space_size=512
    networks:
      - n8n_network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 400M
        reservations:
          memory: 200M
    healthcheck:
      test: ["CMD-SHELL", "until wget --spider -q http://localhost:5678; do echo 'n8n not responding yet...'; sleep 5; done"]
      interval: 15s
      timeout: 5s
      retries: 20

  waha:
    image: devlikeapro/waha
    container_name: waha
    ports:
      - "${WAHA_PORT}:3000"
    networks:
      - n8n_network
    stdin_open: true
    tty: true
    deploy:
      resources:
        limits:
          memory: 300M
        reservations:
          memory: 150M
    healthcheck:
      test: ["CMD-SHELL", "wget --spider -q http://localhost:3000/api/sessions || exit 1"]
      interval: 20s
      timeout: 10s
      retries: 3

  nginx-proxy:
    image: nginx:alpine
    container_name: nginx-proxy
    depends_on:
      n8n:
        condition: service_healthy
      waha:
        condition: service_healthy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx-auth/.htpasswd:/etc/nginx/.htpasswd:ro
    networks:
      - n8n_network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 64M
        reservations:
          memory: 32M

networks:
  n8n_network:
    driver: bridge

volumes:
  postgres_data: